# Generated by Django 3.2.8 on 2021-10-25 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='微信')),
                ('port', models.CharField(default='8080', max_length=64, verbose_name='端口')),
                ('dir', models.CharField(default='/var/lib', max_length=64, verbose_name='目录')),
                ('cpu', models.IntegerField(default=500, verbose_name='核心数')),
                ('ram', models.IntegerField(default=500, verbose_name='内存')),
                ('disk', models.IntegerField(default=500, verbose_name='硬盘')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
